import { TrendingSearch } from '../../types';
import { TrendingProvider } from './types';

export class MockProvider implements TrendingProvider {
  name = 'MockDevelopmentProvider';

  isConfigured(): boolean {
    return process.env.DEVELOPMENT_MODE === 'true';
  }

  async getTrendingSearches(region: string, timeframe: string): Promise<TrendingSearch[]> {
    if (process.env.DEVELOPMENT_MODE !== 'true') {
      throw new Error('MockProvider is strictly forbidden in production. Set DEVELOPMENT_MODE=true for testing.');
    }

    const geo = (region || 'ID').toUpperCase();

    if (geo === 'ID') {
      return [
        {
          id: 'ID-timnas-u23-1',
          keyword: 'Kualifikasi Piala Asia U23',
          rank: 1,
          region: 'ID',
          category: 'Sports',
          traffic: '500K+',
          trend_direction: 'up',
          trend_percentage: '+320%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Garuda Muda bersiap menghadapi laga penentuan di fase grup',
          opportunity_score: 88,
          is_ai_estimate: true
        },
        {
          id: 'ID-film-horor-2',
          keyword: 'Film Horor Pabrik Gula',
          rank: 2,
          region: 'ID',
          category: 'Entertainment',
          traffic: '200K+',
          trend_direction: 'up',
          trend_percentage: '+180%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Tayang perdana raih rekor penonton hari pertama di bioskop',
          opportunity_score: 82,
          is_ai_estimate: true
        },
        {
          id: 'ID-gemini-ai-3',
          keyword: 'Gemini AI Workspace Indonesia',
          rank: 3,
          region: 'ID',
          category: 'Technology',
          traffic: '100K+',
          trend_direction: 'up',
          trend_percentage: '+140%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Fitur baru otomasi dokumen berbasis kecerdasan buatan resmi hadir',
          opportunity_score: 94,
          is_ai_estimate: true
        },
        {
          id: 'ID-saham-ihsg-4',
          keyword: 'IHSG Tembus All Time High',
          rank: 4,
          region: 'ID',
          category: 'Finance',
          traffic: '80K+',
          trend_direction: 'up',
          trend_percentage: '+75%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Saham perbankan pimpin penguatan bursa domestik pekan ini',
          opportunity_score: 79,
          is_ai_estimate: true
        },
        {
          id: 'ID-resep-takjil-5',
          keyword: 'Ide Usaha Minuman Kekinian',
          rank: 5,
          region: 'ID',
          category: 'General',
          traffic: '60K+',
          trend_direction: 'stable',
          trend_percentage: '+45%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Tren waralaba minuman modal kecil laris di kalangan anak muda',
          opportunity_score: 89,
          is_ai_estimate: true
        },
        {
          id: 'ID-kpop-jakarta-6',
          keyword: 'Konser K-Pop Jakarta Tiket',
          rank: 6,
          region: 'ID',
          category: 'Entertainment',
          traffic: '50K+',
          trend_direction: 'up',
          trend_percentage: '+65%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Jadwal presale dan kategori seat plan resmi diumumkan promotor',
          opportunity_score: 75,
          is_ai_estimate: true
        },
        {
          id: 'ID-koleksi-kdp-7',
          keyword: 'Jurnal Perencana Keuangan Syariah',
          rank: 7,
          region: 'ID',
          category: 'Finance',
          traffic: '30K+',
          trend_direction: 'up',
          trend_percentage: '+50%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Meningkatnya minat masyarakat terhadap pengelolaan aset mandiri',
          opportunity_score: 91,
          is_ai_estimate: true
        },
        {
          id: 'ID-gadget-baru-8',
          keyword: 'Smartphone 2 Jutaan Kamera Bagus',
          rank: 8,
          region: 'ID',
          category: 'Technology',
          traffic: '25K+',
          trend_direction: 'stable',
          trend_percentage: '+30%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Rekomendasi ponsel terjangkau dengan sensor 50MP OIS',
          opportunity_score: 86,
          is_ai_estimate: true
        },
        {
          id: 'ID-wisata-alam-9',
          keyword: 'Destinasi Glamping Bandung Barat',
          rank: 9,
          region: 'ID',
          category: 'General',
          traffic: '20K+',
          trend_direction: 'up',
          trend_percentage: '+40%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Lokasi liburan akhir pekan favorit keluarga dengan pemandangan pinus',
          opportunity_score: 77,
          is_ai_estimate: true
        },
        {
          id: 'ID-beasiswa-10',
          keyword: 'Pendaftaran Beasiswa Unggulan',
          rank: 10,
          region: 'ID',
          category: 'General',
          traffic: '20K+',
          trend_direction: 'stable',
          trend_percentage: '+25%',
          source: 'Google Trends (Dev Mock)',
          source_url: 'https://trends.google.com',
          timestamp: new Date().toISOString(),
          created_at: new Date().toISOString(),
          news_title: 'Syarat dokumen dan jadwal seleksi tahap pertama telah dibuka',
          opportunity_score: 80,
          is_ai_estimate: true
        }
      ];
    }

    // Default US mock
    return [
      {
        id: 'US-ai-agents-1',
        keyword: 'Autonomous AI Agents',
        rank: 1,
        region: 'US',
        category: 'Technology',
        traffic: '500K+',
        trend_direction: 'up',
        trend_percentage: '+290%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Next generation workflow automation models disrupt software engineering',
        opportunity_score: 96,
        is_ai_estimate: true
      },
      {
        id: 'US-fed-rate-2',
        keyword: 'Federal Reserve Interest Rate Decision',
        rank: 2,
        region: 'US',
        category: 'Finance',
        traffic: '300K+',
        trend_direction: 'up',
        trend_percentage: '+150%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Treasury yields shift as central bankers convene in monetary policy session',
        opportunity_score: 78,
        is_ai_estimate: true
      },
      {
        id: 'US-smart-ring-3',
        keyword: 'Smart Ring Health Tracking',
        rank: 3,
        region: 'US',
        category: 'Technology',
        traffic: '200K+',
        trend_direction: 'up',
        trend_percentage: '+110%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Wearable biometric tech reaches mainstream adoption with sleep diagnostics',
        opportunity_score: 92,
        is_ai_estimate: true
      },
      {
        id: 'US-premier-league-4',
        keyword: 'Champions League Highlights',
        rank: 4,
        region: 'US',
        category: 'Sports',
        traffic: '150K+',
        trend_direction: 'up',
        trend_percentage: '+85%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Dramatic stoppage-time comeback clinches quarterfinal berth',
        opportunity_score: 74,
        is_ai_estimate: true
      },
      {
        id: 'US-solopreneur-5',
        keyword: 'Micro SaaS Business Ideas',
        rank: 5,
        region: 'US',
        category: 'Finance',
        traffic: '100K+',
        trend_direction: 'up',
        trend_percentage: '+95%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Indie makers build profitable niche digital tools with minimal overhead',
        opportunity_score: 95,
        is_ai_estimate: true
      },
      {
        id: 'US-low-carb-6',
        keyword: 'High Protein Meal Prep for Beginners',
        rank: 6,
        region: 'US',
        category: 'General',
        traffic: '90K+',
        trend_direction: 'stable',
        trend_percentage: '+40%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Affordable grocery lists and kitchen time-saving strategies gain viral traction',
        opportunity_score: 87,
        is_ai_estimate: true
      },
      {
        id: 'US-kdp-coloring-7',
        keyword: 'Mindfulness Coloring Book KDP',
        rank: 7,
        region: 'US',
        category: 'General',
        traffic: '80K+',
        trend_direction: 'up',
        trend_percentage: '+70%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Amazon publishing creators see surging quarterly demand for relaxation series',
        opportunity_score: 93,
        is_ai_estimate: true
      },
      {
        id: 'US-solar-rebates-8',
        keyword: 'Clean Energy Tax Credit 2026',
        rank: 8,
        region: 'US',
        category: 'Finance',
        traffic: '60K+',
        trend_direction: 'stable',
        trend_percentage: '+35%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Homeowners evaluate updated federal incentives for energy storage upgrades',
        opportunity_score: 83,
        is_ai_estimate: true
      },
      {
        id: 'US-indie-movie-9',
        keyword: 'Sci-Fi Thriller Trailer Release',
        rank: 9,
        region: 'US',
        category: 'Entertainment',
        traffic: '50K+',
        trend_direction: 'up',
        trend_percentage: '+55%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Festival award winner releases cryptic first look ahead of theatrical debut',
        opportunity_score: 72,
        is_ai_estimate: true
      },
      {
        id: 'US-mechanical-keyboard-10',
        keyword: 'Custom Wireless Mechanical Keyboard',
        rank: 10,
        region: 'US',
        category: 'Technology',
        traffic: '40K+',
        trend_direction: 'stable',
        trend_percentage: '+30%',
        source: 'Google Trends (Dev Mock)',
        source_url: 'https://trends.google.com',
        timestamp: new Date().toISOString(),
        created_at: new Date().toISOString(),
        news_title: 'Ergonomic desk setups drive enthusiast peripheral sales to new heights',
        opportunity_score: 85,
        is_ai_estimate: true
      }
    ];
  }
}
